baseURL = 'https://dcdadvisory.com/'
languageCode = 'en-us'
title = 'DCD Advisory'
theme = 'PaperMod'
enableRobotsTXT = true

[params]
  description = "DCD Advisory designs brands, websites, automation systems, AI tools, and digital infrastructure built around real business problems."
  author = "Chadwick"

  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  
  # DISBALE THE DEFAULT MOON REACTION TOGGLE
  disableThemeToggle = true

[outputs]
  home = ["HTML"]

[permalinks]
  blog = "/blog/:title/"